### POST
POST http://localhost:3000/user
Content-Type: application/json

{
  "name": "jueun",
  "age": 29,
  "phone": "010-1234-",
  "email": "example2"
}

### GET
GET http://localhost:3000/users/0
Accept: application/json
